### ISSUE TITLE
please tag 0.5 release.

### ISSUE THREAD

**Issue by LocutusOfBorg** [deterministic-arts/DartsPyLRU#3]
Hi, it would be nice if you can git tag the latest commit and push the release, so we can track the tarball here on github.

thanks

**Comment by deterministic-arts** [comment]
The latest (0.5) release has been tagged. It was already the active version on PyPI.

**Comment by LocutusOfBorg** [comment]
thanks a lot!

**Comment by LocutusOfBorg** [comment]
yes, I know it was on PyPI, and this is where I grabbed it, but debian/watch file tracks so much better github, so I would appreciate if you can tag also here :)

**Comment by deterministic-arts** [comment]
If it helps... Hopefully, I will remember to do this the next time, I make a public release :-)
